/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis1;

/**
 *
 * @author Asus
 */
public class kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form kuis1
     */
    public kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NIL = new javax.swing.JTextField();
        MATPEL = new javax.swing.JTextField();
        ABSEN = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HAS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("=-PENILAIAN SISWA-=");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 290, 29);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 40, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 40, 14);

        jLabel4.setText("Matpel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 120, 50, 14);

        jLabel5.setText("Nilai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 40, 14);
        getContentPane().add(NIL);
        NIL.setBounds(90, 140, 140, 30);

        MATPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MATPELActionPerformed(evt);
            }
        });
        getContentPane().add(MATPEL);
        MATPEL.setBounds(90, 110, 140, 30);

        ABSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABSENActionPerformed(evt);
            }
        });
        getContentPane().add(ABSEN);
        ABSEN.setBounds(90, 80, 140, 30);

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });
        getContentPane().add(NAMA);
        NAMA.setBounds(90, 50, 140, 30);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("PROCCES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 190, 100, 23);

        HAS.setColumns(20);
        HAS.setRows(5);
        jScrollPane1.setViewportView(HAS);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 230, 200, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMAActionPerformed

    private void ABSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABSENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABSENActionPerformed

    private void MATPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MATPELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MATPELActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nama = NAMA.getText();
    String abs = ABSEN.getText();
    String MPL= MATPEL.getText();
    int nilai = Integer.parseInt(NIL.getText());
    String Ket = null;
        if (nilai<75) {
            Ket="Tidak Lulus";
        }else if (nilai==75) {
            Ket="Lulus";
        }else if (nilai<85) {
            Ket="Good Joob";
        }else if (nilai>100) {
            Ket="AMAZING!!!";
        }
    HAS.setText("Nama\t:"+nama+"\nAbsen\t:"+abs+"\nMatpel\t:"+MPL+"\nNilai\t:"+nilai+"\nKeterangan\t:"+Ket);
    
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ABSEN;
    private javax.swing.JTextArea HAS;
    private javax.swing.JTextField MATPEL;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
