/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis1;

import javax.swing.ButtonGroup;

/**
 *
 * @author Asus
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        hb4 = new javax.swing.JTextField();
        hb3 = new javax.swing.JTextField();
        hb2 = new javax.swing.JTextField();
        hb1 = new javax.swing.JTextField();
        pro = new javax.swing.JButton();
        hp = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ha = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("Harga barang 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 100, 14);

        jLabel2.setText("Harga barang 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 100, 14);

        jLabel3.setText("Harga barang 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 100, 14);

        jLabel4.setText("Harga barang 4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 100, 14);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 170, 50, 14);

        jLabel6.setText("=-PEMBAYARAN-=");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 10, 91, 14);
        getContentPane().add(diskon);
        diskon.setBounds(130, 160, 180, 30);
        getContentPane().add(hb4);
        hb4.setBounds(130, 130, 180, 30);
        getContentPane().add(hb3);
        hb3.setBounds(130, 100, 180, 30);
        getContentPane().add(hb2);
        hb2.setBounds(130, 70, 180, 30);
        getContentPane().add(hb1);
        hb1.setBounds(130, 40, 180, 30);

        pro.setText("Proses");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        getContentPane().add(pro);
        pro.setBounds(40, 210, 70, 23);

        hp.setText("Hapus");
        hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpActionPerformed(evt);
            }
        });
        getContentPane().add(hp);
        hp.setBounds(160, 210, 80, 23);

        ex.setText("Keluar");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        getContentPane().add(ex);
        ex.setBounds(280, 210, 80, 23);

        ha.setColumns(20);
        ha.setRows(5);
        jScrollPane1.setViewportView(ha);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 260, 280, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        double harg1= Double.parseDouble(hb1.getText());
        double harg2= Double.parseDouble(hb2.getText());
        double harg3= Double.parseDouble(hb3.getText());
        double harg4= Double.parseDouble(hb4.getText());
        double hasil = harg1+harg2+harg3+harg4;
        double disk = Double.parseDouble(diskon.getText());
        double diss = disk/100*hasil;
        double harga= hasil-diss;
        ha.setText("Harga barang 1\t:"+harg1+"\nHarga barang 2\t:"+harg2+"\nHarga barang 3\t:"+harg3+"\nHarga barang 4\t:"+harg4+"\nDiskon\t:"+diss+"\nTotal bayar\t:"+harga);
    }//GEN-LAST:event_proActionPerformed

    private void hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpActionPerformed
        ha.setText("");
        hb1.setText("");
        hb2.setText("");
        hb3.setText("");
        hb4.setText("");
        diskon.setText("");
        
    }//GEN-LAST:event_hpActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
    dispose();         
    }//GEN-LAST:event_exActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diskon;
    private javax.swing.JButton ex;
    private javax.swing.JTextArea ha;
    private javax.swing.JTextField hb1;
    private javax.swing.JTextField hb2;
    private javax.swing.JTextField hb3;
    private javax.swing.JTextField hb4;
    private javax.swing.JButton hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pro;
    // End of variables declaration//GEN-END:variables
}
