/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UjiKebolehan;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Ujikebolehan extends javax.swing.JFrame {

    /**
     * Creates new form Ujikebolehan
     */
    public Ujikebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        perr = new javax.swing.JRadioButton();
        LL = new javax.swing.JRadioButton();
        tii = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ide = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 14);

        jLabel2.setText("Tinggi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 60, 14);

        jLabel3.setText("Berat Badan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 70, 14);

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 100, 20);

        jLabel5.setText("cm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 90, 20, 14);

        jLabel6.setText("kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 120, 20, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Berat Badan Ideal anda adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 210, 200, 20);

        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 210, 30, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 270, 190, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 10, 140, 20);

        pp.add(perr);
        perr.setText("Perempuan");
        perr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perrActionPerformed(evt);
            }
        });
        getContentPane().add(perr);
        perr.setBounds(100, 150, 90, 23);

        pp.add(LL);
        LL.setText("Laki-Laki");
        getContentPane().add(LL);
        LL.setBounds(210, 150, 80, 23);
        getContentPane().add(tii);
        tii.setBounds(80, 80, 50, 30);
        getContentPane().add(bb);
        bb.setBounds(80, 110, 50, 30);
        getContentPane().add(nm);
        nm.setBounds(80, 40, 150, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 180, 80, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(13, 180, 90, 23);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Coba Lagi");
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 180, 100, 23);
        getContentPane().add(ide);
        ide.setBounds(210, 210, 90, 20);
        getContentPane().add(hasil);
        hasil.setBounds(10, 290, 360, 30);
        getContentPane().add(saran);
        saran.setBounds(10, 330, 360, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            int ti = Integer.parseInt(tii.getText());
            int bt = Integer.parseInt(bb.getText());
            String nama = nm.getText();
            int kideal = 0;
            if (perr.isSelected()) {
                kideal = ti - 100;
            } else if (LL.isSelected()) {
                kideal = ti - 104;
            }
            String temp = Integer.toString(kideal);

            if (kideal < bt) {
                ide.setText(temp);
                hasil.setText("Maaf " + nm.getText() + " , Sepertinya anda Overweight :( ");
                saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
            } else if (kideal > bt) {
                ide.setText(temp);
                hasil.setText("Maaf " + nm.getText() + " , Sepertinya anda Underweight :( ");
                saran.setText("Banyaklah menkonsumsi makanan yang berkabohidrat");
            } else {
                ide.setText(temp);
                hasil.setText("Hallo " + nm.getText() + " , Berat badan anda sudah ideal :) ");
                saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :) ");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kotak Input Belum Terisi Semua" , "Message",
                    JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ujikebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LL;
    private javax.swing.JTextField bb;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ide;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nm;
    private javax.swing.JRadioButton perr;
    private javax.swing.ButtonGroup pp;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tii;
    // End of variables declaration//GEN-END:variables
}
